# Generated by Django 4.1.3 on 2022-11-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_doctors_photo_alter_doctors_special_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='achiv',
            field=models.TextField(help_text='Регалии и достижения врача', verbose_name='Достижения'),
        ),
    ]
