# Generated by Django 4.1.3 on 2022-11-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_doctors_achiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='achiv_short',
            field=models.CharField(default=12, help_text='Выдаются в боте при выборе врача', max_length=255, verbose_name='Основные достижения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(help_text='Имя клиента', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(help_text='Телефон клиента', max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='tg_id',
            field=models.BigIntegerField(default=0, help_text='Telegram ID для записи через бот и оповещения', verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='achiv',
            field=models.TextField(help_text='Выдаются в боте при просмотре информации о враче', verbose_name='Достижения и образование'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='email',
            field=models.EmailField(help_text='Почта для оповещения о записи клиентов', max_length=254, verbose_name='Почта врача'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='experiens',
            field=models.IntegerField(help_text='Стаж в годах', verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='records',
            name='finish',
            field=models.BooleanField(help_text='Запланирован или закончен примем клиента', verbose_name='Прием окончен'),
        ),
        migrations.AlterField(
            model_name='specials',
            name='name',
            field=models.CharField(default='', help_text='Укажите название специальности', max_length=200, unique=True, verbose_name='Название специальности'),
        ),
    ]
