# Generated by Django 4.1.3 on 2022-11-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_clients_photo_alter_doctors_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='achiv',
            field=models.TextField(help_text='Выдаются в боте при просмотре информации о враче', max_length=4000, verbose_name='Достижения и образование'),
        ),
    ]
