# Generated by Django 4.1.3 on 2022-11-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_remove_clients_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='achiv',
            field=models.TextField(help_text='Выдаются в боте при просмотре информации о враче', max_length=1000, verbose_name='Достижения и образование'),
        ),
        migrations.AlterField(
            model_name='records',
            name='finish',
            field=models.BooleanField(default=False, help_text='Запланирован или закончен примем клиента', verbose_name='Прием окончен'),
        ),
    ]
